baseurl: '/betygssnittet'
exclude: ['README.md']
permalink: pretty
title: 'Betygssnittet'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'All rights reserved. (C) Isak Engström 2017-2021.'

seo:
  meta_og_title: "Betygssnittet"
  meta_og_type: "website"
  meta_og_url: "https://isakcodes.github.io"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Betygssnittet. Räknar ut ditt betygssnitt automatiskt i Ladok"
  meta_twitter_card: "Betygssnittet. Räknar ut ditt betygssnitt automatiskt i Ladok"
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
